-- https://leetcode.com/problems/employees-earning-more-than-their-managers/
SELECT
	A.EMPLOYEE_NAME AS EMPLOYEE
FROM (SELECT
		  A.NAME AS MANAGER_NAME
		   , B.NAME AS EMPLOYEE_NAME
		   , A.SALARY AS MANAGER_SALARY
		   , B.SALARY AS EMPLOYEE_SALARY
	  FROM EMPLOYEE A, EMPLOYEE B
	  WHERE A.ID = B.MANAGERID) A
WHERE A.MANAGER_SALARY < A.EMPLOYEE_SALARY

SELECT
	A.NAME AS EMPLOYEE
FROM EMPLOYEE A
WHERE EXISTS(SELECT 1 FROM EMPLOYEE B WHERE A.MANAGERID = B.ID AND A.SALARY > B.SALARY)

SELECT
	A.NAME AS EMPLOYEE
FROM EMPLOYEE A, EMPLOYEE B
WHERE A.MANAGERID = B.ID
	AND A.SALARY > B.SALARY