-- https://leetcode.com/problems/duplicate-emails/
SELECT
	EMAIL
FROM PERSON
GROUP BY EMAIL
HAVING COUNT(EMAIL) > 1

SELECT
	DISTINCT A.EMAIL
FROM PERSON A
WHERE EXISTS (SELECT 1 FROM PERSON B WHERE A.EMAIL = B.EMAIL AND A.ID != B.ID)