-- https://leetcode.com/problems/department-top-three-salaries/
SELECT
	DEPARTMENT
	 , EMPLOYEE
	 , SALARY
FROM (SELECT
		  B.NAME AS DEPARTMENT
		   , A.NAME AS EMPLOYEE
		   , A.SALARY AS SALARY
		   , DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RANK
	  FROM EMPLOYEE A, DEPARTMENT B
	  WHERE A.DEPARTMENTID = B.ID)
WHERE RANK BETWEEN 1 AND 3;

SELECT
	DEPARTMENT
	 , EMPLOYEE
	 , SALARY
FROM (SELECT
		  B.NAME AS DEPARTMENT
		   , A.NAME AS EMPLOYEE
		   , A.SALARY AS SALARY
		   , DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RANK
	  FROM EMPLOYEE A, DEPARTMENT B
	  WHERE A.DEPARTMENTID = B.ID)
WHERE RANK <= 3;

SELECT
	DEPARTMENT
	 , EMPLOYEE
	 , SALARY
FROM (SELECT
		  B.NAME AS DEPARTMENT
		   , A.NAME AS EMPLOYEE
		   , A.SALARY AS SALARY
		   , DENSE_RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RANK
	  FROM EMPLOYEE A, DEPARTMENT B
	  WHERE A.DEPARTMENTID = B.ID)
WHERE RANK IN (1, 2, 3);