-- https://leetcode.com/problems/department-highest-salary/
SELECT
	B.NAME AS DEPARTMENT
	 , A.NAME AS EMPLOYEE
	 , A.SALARY AS SALARY
FROM (SELECT
		  NAME
		   , SALARY
		   , MAX(SALARY) OVER (PARTITION BY DEPARTMENTID) AS MAX_SALARY
		   , DEPARTMENTID
	  FROM EMPLOYEE) A, DEPARTMENT B
WHERE A.DEPARTMENTID = B.ID
	AND A.SALARY = A.MAX_SALARY